language: generic

sudo: required

env:
    global:
        - VERSION=7.4.0
        - SERVER=wildlfy
        - BUILD=camundawildfly_camunda-h2
        - IMAGE=menski/camunda-bpm-platform-new
        - COMPOSE_PROJECT_NAME=camunda-wildfly

services:
    - docker

before_script:
    # build image
    - docker-compose build
    # display images
    - docker images


script:
    # start and test h2 image
    - docker-compose up -d camunda-h2
    - ./test-container.sh
    - docker-compose stop
    - docker-compose rm -f

    # start and test postgresql image
    - docker-compose up -d postgresql && sleep 5
    - docker-compose up -d camunda-postgresql
    - ./test-container.sh
    - docker-compose stop
    - docker-compose rm -f

    # start and test mysql image
    - docker-compose up -d mysql && sleep 20
    - docker-compose up -d camunda-mysql
    - ./test-container.sh
    - docker-compose stop
    - docker-compose rm -f

    # tag images
    - docker tag $BUILD $IMAGE:SNAPSHOT
    - docker tag $BUILD $IMAGE:$VERSION-SNAPSHOT
    - docker tag $BUILD $IMAGE:$SERVER-SNAPSHOT
    - docker tag $BUILD $IMAGE:$SERVER-$VERSION-SNAPSHOT

    # display images
    - docker images

after_success:
    # login to docker hub
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    # push images
    - docker push $IMAGE:SNAPSHOT
    - docker push $IMAGE:$VERSION-SNAPSHOT
    - docker push $IMAGE:$SERVER-SNAPSHOT
    - docker push $IMAGE:$SERVER-$VERSION-SNAPSHOT
